### ISSUE TITLE
Fatal error: Can't use method return value in write context in /var/www/spotweb/lib/page/SpotPage_newznabapi.php on line 173

### ISSUE THREAD

**Issue by MrMennens** [mesa57/spotweb#2]
i'm Trying to fix my sonarr/spotweb linking, but i'm unable to get it to work..

with the newest branch i'm getting this error:

Fatal error: Can't use method return value in write context in /var/www/spotweb/lib/page/SpotPage_newznabapi.php on line 173

With the normal version i'm getting:
<error code="200" description="Missing parameter"/>

anyone any tips on where to go from here?

(i'm using a raspberry pi on Raspbian (Minibian) with spotweb and Nginx)

**Comment by mesa57** [comment]
Is it possible for you to look in the Sonarr logs to determine how the spotweb api was called ?

**Comment by MrMennens** [comment]
Sorry for the delay.
Sonarr calls:
http://mylocalip/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<myapikey>&offset=0&limit=100&q=27811&season=5&ep=4

**Comment by mesa57** [comment]
In my case it returns a normal empty result : 
```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/">
  <channel>
    <atom:link href="http://localhost/spotweb/api" rel="self" type="application/rss+xml"/>
    <title>Spotweb Index</title>
    <description>Spotweb Index API Results</description>
    <link>http://localhost/spotweb/</link>
    <language>en-gb</language>
    <webMaster>john@example.com (Jane Doe)</webMaster>
    <category/>
    <image>
      <url>http://localhost/spotweb/images/spotnet.gif</url>
      <title>Spotweb Index</title>
      <link>http://localhost/spotweb/</link>
      <description>SpotWeb Index API Results</description>
    </image>
    <newznab:response offset="0" total="0"/>
  </channel>
</rss>
```

I suppose you should check if you downloaded and installed the correct version

**Comment by mesa57** [comment]
It is also strange that Sonarr is doing a query with the q= parameter and gives a rageid as search (q=27811).
That should not happen with the current release of spotweb. Sonarr should give priority to the rid= parameter and then, if not found, the tvmaze= and finally the q={name to be searched}

I strongly advise you to post this problem to the Sonarr forum.

**Comment by Longshot** [comment]
I'm getting the same error after updating spotweb the other day.
Both SB and CP are complaining about not being able to load the spotweb rss feed and https://myserver.nl/api?t=c is giving me this error.

**Comment by mesa57** [comment]
What php version are you on ?

**Comment by Longshot** [comment]
PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31)
